import { Customer } from '../customer/entities/customer.entity';

export const customersDummyData: Customer[] = [
  {
    id: 'abcd1',
    firstName: 'Leslie',
    lastName: 'Goldman',
    email: 'lg1@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd2',
    firstName: 'Leslie2',
    lastName: 'Goldman',
    email: 'lg2@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd3',
    firstName: 'Leslie3',
    lastName: 'Goldman',
    email: 'lg3@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd4',
    firstName: 'Leslie4',
    lastName: 'Goldman',
    email: 'lg4@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd5',
    firstName: 'Leslie5',
    lastName: 'Goldman',
    email: 'lg5@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd6',
    firstName: 'Leslie6',
    lastName: 'Goldman',
    email: 'lg6@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd7',
    firstName: 'Leslie7',
    lastName: 'Goldman',
    email: 'lg7@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd8',
    firstName: 'Leslie8',
    lastName: 'Goldman',
    email: 'lg8@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd9',
    firstName: 'Leslie9',
    lastName: 'Goldman',
    email: 'lg9@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd10',
    firstName: 'Leslie10',
    lastName: 'Goldman',
    email: 'lg10@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd11',
    firstName: 'Leslie11',
    lastName: 'Goldman',
    email: 'lg11@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd12',
    firstName: 'Leslie12',
    lastName: 'Goldman',
    email: 'lg12@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd13',
    firstName: 'Leslie13',
    lastName: 'Goldman',
    email: 'lg13@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd14',
    firstName: 'Leslie14',
    lastName: 'Goldman',
    email: 'lg14@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd15',
    firstName: 'Leslie15',
    lastName: 'Goldman',
    email: 'lg15@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd16',
    firstName: 'Leslie16',
    lastName: 'Goldman',
    email: 'lg16@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd17',
    firstName: 'Leslie17',
    lastName: 'Goldman',
    email: 'lg17@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd18',
    firstName: 'Leslie18',
    lastName: 'Goldman',
    email: 'lg18@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd19',
    firstName: 'Leslie19',
    lastName: 'Goldman',
    email: 'lg19@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd20',
    firstName: 'Leslie20',
    lastName: 'Goldman',
    email: 'lg20@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd21',
    firstName: 'Leslie21',
    lastName: 'Goldman',
    email: 'lg21@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd22',
    firstName: 'Leslie22',
    lastName: 'Goldman',
    email: 'lg22@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd23',
    firstName: 'Leslie23',
    lastName: 'Goldman',
    email: 'lg23@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd24',
    firstName: 'Leslie24',
    lastName: 'Goldman',
    email: 'lg24@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
  {
    id: 'abcd25',
    firstName: 'Leslie25',
    lastName: 'Goldman',
    email: 'lg25@gmail.com',
    registrationDate: new Date('2022-10-22'),
  },
] as const;
